POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "j@j.com"
}

### 

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "[UUID]"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "123",
    "account_id_to": "456",
    "amount": 5
}
